//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobilePhoneStoreDBMS.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specifications_of_all_product
    {
        public string name { get; set; }
        public string specification { get; set; }
        public string Value { get; set; }
    }
}
